"""Assemble ``notebooks/book_figures.ipynb`` from the per-chapter source files.

Usage::

    .venv/bin/python tools/build_book_notebook.py [--output PATH] [--check] [--expect N]

Each chapter of Ramsay, Hooker & Graves (2009) lives in its own plain Python file
``notebooks/book/chNN_<slug>.py`` written in the jupytext "percent" format:

* ``# %% [markdown]`` starts a markdown cell; every following line is ``#``
  followed by one space and the text (a bare ``#`` is an empty line).
* ``# %%`` starts a code cell.

The chapter contract checked here:

1. The first cell is markdown whose first line is ``# Chapter N: <title>``, with
   ``N`` equal to the number in the file name.
2. The second cell is code (the chapter's imports) and sets
   ``plt.rcParams["figure.max_open_warning"] = 0``.
3. A figure is a markdown cell whose first line is exactly ``### Figure N.M``
   (``N`` the chapter), followed directly by a code cell whose last line is the
   bare expression ``fig`` (a trailing comment such as ``# noqa: B018`` is allowed).
4. Code cells never call ``plt.show()`` and never touch ``fabel._internal``.

Across the book, figure numbers must be unique and strictly increasing.  The
tool reads only these source files and writes the notebook with ``nbformat``
(no jupytext needed); outputs are left empty so the notebook is executed fresh,
e.g. by ``pytest --nbmake``.

Exit status is ``0`` on success and ``1`` when a chapter breaks the contract or
the total figure count differs from ``--expect``.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO_ROOT / "notebooks" / "book"
OUTPUT = REPO_ROOT / "notebooks" / "book_figures.ipynb"

CellKind = Literal["markdown", "code"]

_CHAPTER_FILE = re.compile(r"^ch(\d{2})_[a-z0-9_]+\.py$")
_CHAPTER_HEADING = re.compile(r"^# Chapter (\d+): (\S.*)$")
_FIGURE_HEADING = re.compile(r"^### Figure (\d+)\.(\d+)$")
_FIG_LINE = re.compile(r"^fig(\s+#.*)?$")
_MAX_OPEN_WARNING = re.compile(r"""plt\.rcParams\[["']figure\.max_open_warning["']\]\s*=\s*0\b""")
_FORBIDDEN_CODE = {
    "plt.show(": "calls plt.show()",
    "fabel._internal": "uses fabel._internal (public API only)",
}

TITLE = """\
# Functional Data Analysis with R and MATLAB: the figures in Fabel

This notebook rebuilds the figures of J. O. Ramsay, G. Hooker and S. Graves
(2009), *Functional Data Analysis with R and MATLAB*, Springer (Use R! series),
with the public API of Fabel only. It is generated by
`tools/build_book_notebook.py` from the chapter files in `notebooks/book/`;
edit those files, not this notebook.

**Data.** `growth`, `gait` and `pinch` ship inside the package. The other book
datasets are downloaded on first use from the `data-v1` GitHub release of the
project, checked against a SHA-256 checksum and cached in `~/.cache/fabel`. Set
the environment variable `FABEL_DATA_DIR` to use another cache directory, or to
point at a local copy of the release files (for example the `data_release/`
directory written by `tools/build_data_release.py`). Where the book uses data
that Fabel does not ship, the figure's text says what was used instead.

**Run it.** `pytest --nbmake notebooks/book_figures.ipynb` executes every cell;
each chapter file also runs on its own with
`MPLBACKEND=Agg python notebooks/book/chNN_<name>.py`.
"""


class BookError(ValueError):
    """A chapter file breaks the chapter contract."""


@dataclass(frozen=True)
class Cell:
    """One notebook cell parsed from a percent-format file.

    Attributes
    ----------
    kind : {"markdown", "code"}
        The cell type.
    source : str
        The cell text, markdown without its ``# `` prefixes, with leading and
        trailing blank lines removed.
    """

    kind: CellKind
    source: str


@dataclass(frozen=True)
class Chapter:
    """A validated chapter file.

    Attributes
    ----------
    number : int
        Chapter number from the file name.
    title : str
        Title from the ``# Chapter N: <title>`` heading.
    path : pathlib.Path
        The source file.
    cells : tuple of Cell
        Every cell of the chapter, in order.
    figures : tuple of tuple of int
        ``(chapter, figure)`` numbers in order of appearance.
    """

    number: int
    title: str
    path: Path
    cells: tuple[Cell, ...]
    figures: tuple[tuple[int, int], ...]


def _trim(lines: list[str]) -> str:
    """Join ``lines`` after dropping blank lines at both ends."""
    start, end = 0, len(lines)
    while start < end and not lines[start].strip():
        start += 1
    while end > start and not lines[end - 1].strip():
        end -= 1
    return "\n".join(lines[start:end])


def _markdown_line(line: str, lineno: int, name: str) -> str:
    """Strip the comment prefix from one markdown line."""
    if line.rstrip() == "#":
        return ""
    if line.startswith("# "):
        return line[2:]
    if not line.strip():
        return ""
    raise BookError(f"{name}:{lineno}: markdown line must start with '# ': {line!r}")


def parse_percent(text: str, name: str = "<string>") -> list[Cell]:
    """Split a percent-format Python file into notebook cells.

    Parameters
    ----------
    text : str
        The file contents.
    name : str, optional
        File name used in error messages.

    Returns
    -------
    list of Cell
        The cells in file order.

    Raises
    ------
    BookError
        If there is text before the first cell marker, an unknown cell marker,
        a markdown line without the ``# `` prefix, or an empty cell.
    """
    cells: list[Cell] = []
    kind: CellKind | None = None
    body: list[str] = []
    start = 0

    def close() -> None:
        if kind is None:
            return
        source = _trim(body)
        if not source:
            raise BookError(f"{name}:{start}: empty {kind} cell")
        cells.append(Cell(kind, source))

    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.rstrip()
        if line.startswith("# %%"):
            close()
            marker = line[4:].strip()
            if marker == "[markdown]":
                kind = "markdown"
            elif marker == "":
                kind = "code"
            else:
                raise BookError(f"{name}:{lineno}: unknown cell marker {line!r}")
            body = []
            start = lineno
        elif kind is None:
            if line.strip():
                raise BookError(f"{name}:{lineno}: text before the first cell marker")
        elif kind == "markdown":
            body.append(_markdown_line(line, lineno, name))
        else:
            body.append(line)
    close()
    return cells


def _check_figure_code(cell: Cell, label: str, name: str) -> None:
    """Check that a figure's code cell ends in the bare expression ``fig``."""
    if cell.kind != "code":
        raise BookError(f"{name}: Figure {label} heading is not followed by a code cell")
    if _FIG_LINE.match(cell.source.splitlines()[-1]) is None:
        raise BookError(f"{name}: the code cell of Figure {label} must end with 'fig'")


def validate_chapter(path: Path, cells: Sequence[Cell]) -> Chapter:
    """Check one chapter against the chapter contract.

    Parameters
    ----------
    path : pathlib.Path
        The chapter file; its name gives the chapter number.
    cells : sequence of Cell
        The parsed cells of that file.

    Returns
    -------
    Chapter
        The chapter with its title and figure numbers.

    Raises
    ------
    BookError
        If the file name, heading, import cell or any figure breaks the contract.
    """
    name = path.name
    match = _CHAPTER_FILE.match(name)
    if match is None:
        raise BookError(f"{name}: chapter files must be named chNN_<slug>.py")
    number = int(match.group(1))
    if len(cells) < 2:
        raise BookError(f"{name}: needs a heading cell and an import cell")
    head, imports = cells[0], cells[1]
    heading = _CHAPTER_HEADING.match(head.source.splitlines()[0])
    if head.kind != "markdown" or heading is None:
        raise BookError(f"{name}: first cell must be markdown '# Chapter N: <title>'")
    if int(heading.group(1)) != number:
        raise BookError(f"{name}: heading says chapter {heading.group(1)}, file says {number}")
    if imports.kind != "code" or _MAX_OPEN_WARNING.search(imports.source) is None:
        raise BookError(
            f"{name}: second cell must be code setting plt.rcParams['figure.max_open_warning'] = 0"
        )

    figures: list[tuple[int, int]] = []
    for index, cell in enumerate(cells):
        if cell.kind == "code":
            for needle, problem in _FORBIDDEN_CODE.items():
                if needle in cell.source:
                    raise BookError(f"{name}: a code cell {problem}")
            continue
        lines = cell.source.splitlines()
        if any(_FIGURE_HEADING.match(line) for line in lines[1:]):
            raise BookError(f"{name}: a figure heading must be the first line of its cell")
        figure = _FIGURE_HEADING.match(lines[0])
        if figure is None:
            if lines[0].startswith("### Figure"):
                raise BookError(f"{name}: malformed figure heading {lines[0]!r}")
            continue
        label = f"{figure.group(1)}.{figure.group(2)}"
        if int(figure.group(1)) != number:
            raise BookError(f"{name}: Figure {label} does not belong to chapter {number}")
        if index + 1 >= len(cells):
            raise BookError(f"{name}: Figure {label} heading is not followed by a code cell")
        _check_figure_code(cells[index + 1], label, name)
        figures.append((number, int(figure.group(2))))
    return Chapter(number, heading.group(2).strip(), path, tuple(cells), tuple(figures))


def validate_book(chapters: Sequence[Chapter]) -> None:
    """Check chapter order and figure numbering across the whole book.

    Parameters
    ----------
    chapters : sequence of Chapter
        Chapters in the order they will appear.

    Raises
    ------
    BookError
        If two chapters share a number, chapters are out of order, or figure
        numbers repeat or decrease.
    """
    previous_chapter = 0
    previous_figure: tuple[int, int] = (0, 0)
    for chapter in chapters:
        if chapter.number <= previous_chapter:
            raise BookError(
                f"{chapter.path.name}: chapter {chapter.number} is duplicated or out of order"
            )
        previous_chapter = chapter.number
        for figure in chapter.figures:
            if figure <= previous_figure:
                label = f"{figure[0]}.{figure[1]}"
                raise BookError(
                    f"{chapter.path.name}: Figure {label} is duplicated or out of order"
                )
            previous_figure = figure


def discover(source_dir: Path) -> list[Path]:
    """Return the chapter files of ``source_dir`` in chapter order.

    Parameters
    ----------
    source_dir : pathlib.Path
        Directory holding ``chNN_<slug>.py`` files.

    Returns
    -------
    list of pathlib.Path
        Files sorted by chapter number, then name.

    Raises
    ------
    BookError
        If no chapter file is found.
    """
    paths = [p for p in source_dir.glob("ch*.py") if p.is_file()]
    if not paths:
        raise BookError(f"no chapter files (ch*.py) in {source_dir}")

    def order(path: Path) -> tuple[int, str]:
        match = _CHAPTER_FILE.match(path.name)
        return (int(match.group(1)) if match else 10**6, path.name)

    return sorted(paths, key=order)


def load_chapters(source_dir: Path) -> list[Chapter]:
    """Parse and validate every chapter file of ``source_dir``.

    Parameters
    ----------
    source_dir : pathlib.Path
        Directory holding the chapter files.

    Returns
    -------
    list of Chapter
        The validated chapters, in order.

    Raises
    ------
    BookError
        If any chapter or the book as a whole breaks the contract.
    """
    chapters = []
    for path in discover(source_dir):
        cells = parse_percent(path.read_text(encoding="utf-8"), path.name)
        chapters.append(validate_chapter(path, cells))
    validate_book(chapters)
    return chapters


def build_notebook(chapters: Sequence[Chapter]) -> nbformat.NotebookNode:
    """Build the book notebook: a title cell, then every chapter's cells.

    Parameters
    ----------
    chapters : sequence of Chapter
        Validated chapters in order.

    Returns
    -------
    nbformat.NotebookNode
        A version 4 notebook with no outputs and a ``python3`` kernelspec.
    """
    # nbformat ships without type annotations, hence the targeted ignores below.
    cells = [new_markdown_cell(TITLE.strip())]  # type: ignore[no-untyped-call]
    for chapter in chapters:
        for cell in chapter.cells:
            if cell.kind == "markdown":
                cells.append(new_markdown_cell(cell.source))  # type: ignore[no-untyped-call]
            else:
                cells.append(new_code_cell(cell.source))  # type: ignore[no-untyped-call]
    notebook: nbformat.NotebookNode = new_notebook(  # type: ignore[no-untyped-call]
        cells=cells,
        metadata={
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
    )
    nbformat.validate(notebook)
    return notebook


def figure_table(chapters: Sequence[Chapter]) -> str:
    """Format the per-chapter figure counts as a text table.

    Parameters
    ----------
    chapters : sequence of Chapter
        Validated chapters.

    Returns
    -------
    str
        One row per chapter and a total row.
    """
    rows = [f"{'chapter':>7}  {'figures':>7}  file"]
    for chapter in chapters:
        rows.append(f"{chapter.number:>7}  {len(chapter.figures):>7}  {chapter.path.name}")
    total = sum(len(chapter.figures) for chapter in chapters)
    rows.append(f"{'total':>7}  {total:>7}")
    return "\n".join(rows)


def main(argv: Sequence[str] | None = None) -> int:
    """Run the command-line tool.

    Parameters
    ----------
    argv : sequence of str, optional
        Arguments; defaults to ``sys.argv[1:]``.

    Returns
    -------
    int
        Exit status: ``0`` on success, ``1`` on a contract or count failure.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=Path, default=SOURCE_DIR, help="chapter directory")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="notebook to write")
    parser.add_argument("--check", action="store_true", help="validate only, write nothing")
    parser.add_argument("--expect", type=int, default=None, help="required total figure count")
    args = parser.parse_args(argv)

    try:
        chapters = load_chapters(args.source)
    except BookError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(figure_table(chapters))
    total = sum(len(chapter.figures) for chapter in chapters)
    if args.expect is not None and total != args.expect:
        print(f"error: expected {args.expect} figures, found {total}", file=sys.stderr)
        return 1
    notebook = build_notebook(chapters)
    if args.check:
        print("check passed")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    nbformat.write(notebook, str(args.output))  # type: ignore[no-untyped-call]
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
